MSPB-178: Fixed URL validation in Customized Call Recording
2600hz/monster-ui-voip pull request #345
Opened 2021-02-09 19:24 UTC by ramandeepromana

2021-02-10 16:33 UTC, guillegr123 requested changes

2021-02-10 16:33 UTC, guillegr123 commented on app.js
> +								protocol: [
Looking at the source code, [the name of the validation rule was right](https://github.com/2600hz/monster-ui/blob/master/src/js/lib/monster.ui.js#L1347).  Maybe is it caused by that [`protocols()`](https://github.com/2600hz/monster-ui/blob/master/src/js/lib/monster.ui.js#L1347) method?

2021-02-10 20:24 UTC, azefiel commented
https://github.com/2600hz/monster-ui-voip/pull/346

2021-07-26 16:06 UTC, azefiel commented
fixed by https://github.com/2600hz/monster-ui/pull/885

2021-07-26 16:06 UTC, closed without merging