MSPB-70: Implement Office holidays, make it more user friendly
2600hz/monster-ui-voip pull request #349
Opened 2021-02-18 06:23 UTC by pcandia

2021-02-19 20:29 UTC, guillegr123 requested changes

2021-02-19 20:29 UTC, guillegr123 commented on submodules/strategy/strategy.js
> -		strategyDeleteRuleSet: function(id, callback) {
The function `strategyDeleteRuleSet` is already referenced at the function `strategyGetDetailRuleSet`.

2021-02-19 20:29 UTC, guillegr123 commented on submodules/strategy/strategy.js
> +				$template.find('.duplicate-name-error').slideUp(200);
This could be shortened a bit:
```suggestion
				$template.find('.no-name-error')[isEmpty ? 'slideDown' : 'slideUp'](200)
					.siblings().slideUp(200);
```

2021-02-19 20:29 UTC, guillegr123 commented on submodules/strategyHolidays/strategyHolidays.js
> +							isNewRecurring = _.get(data, 'holidayData.recurring', false);
The variable `isNewRecurring` is not used.

2021-02-19 20:29 UTC, guillegr123 commented on submodules/strategyHolidays/strategyHolidays.js
> +				if (isRecurring && isChecked || !isRecurring) {
Group operations with parenthesis, for clarity.

2021-02-19 20:29 UTC, guillegr123 commented on submodules/strategyHolidays/strategyHolidays.js
> +								}
Missing semicolon.
```suggestion
								};
```

2021-02-19 20:29 UTC, guillegr123 commented on submodules/strategyHolidays/strategyHolidays.js
> +						hasActiveRules = _.some(rulesIds, _.partial(_.includes, activeRulesIds)),
The variable `hasActiveRules` is not used.

2021-02-19 20:29 UTC, guillegr123 commented on submodules/strategyHolidays/strategyHolidays.js
> +
This empty line should be deleted, to follow linting rules: `Block must not be padded by blank lines. eslint(padded-blocks)`

2021-03-02 16:21 UTC, pcandia commented on submodules/strategy/strategy.js
> -		strategyDeleteRuleSet: function(id, callback) {
Good catch!

2021-03-03 14:12 UTC, guillegr123 approved these changes
Lgtm! Is there a PR for branch `5.0`?

2021-03-03 16:00 UTC, pcandia commented
@guillegr123 no, just master. This is new work so eventually it will get merged to 5.1

2021-03-03 16:08 UTC, merged