MSPB-182: Auto enabled voicemail to email when toggling voicemail on
2600hz/monster-ui-voip pull request #363
Opened 2021-03-16 02:55 UTC by azefiel

2021-03-19 22:35 UTC, guillegr123 requested changes

2021-03-19 22:35 UTC, guillegr123 commented on submodules/users/users.js
> +									vm_to_email_enabled: enabled ? vmToEmailEnabled : null
Patching the user with `vm_to_email_enabled = null` does not apply any change to the user document. Could it be set to `false`? Or could the user patch be skipped when `enabled` is `false`?

2021-03-19 23:59 UTC, azefiel commented on submodules/users/users.js
> +									vm_to_email_enabled: enabled ? vmToEmailEnabled : null
On one hand, setting a prop to `null` on PATCH requests [removes](https://docs.2600hz.com/supported/applications/crossbar/doc/basics/#request-data) it from the entity. On the other hand, if the entity's schema declares a default value for that prop, it will be set to that value when missing (i.e. this prop has to be present on the document).

The purpose of doing this is for the UI not to have to know defaults for each prop.

So in this case, when patching a user document with `vm_to_email_enabled: null` where the original value was `false`, the updated result will contain `vm_to_email_enabled: true`, while if the original value was `true`, the updated result will contain `vm_to_email_enabled: true` (which is I think the used case that tricked you into thinking no change was applied?).

Now, we only want to reset that setting when the voicemail feature is disabled so that when enabling it again the UX is identical whether it's the first or nth time this feature has been activated.

2021-04-14 16:08 UTC, guillegr123 commented on submodules/users/users.js
> +									vm_to_email_enabled: enabled ? vmToEmailEnabled : null
Oh, I got it now. I thought that the `null` value was always intended to remove the property from the document.

Sorry for the delay in checking this comment, I think I have missed GitHub's notification from my mail inbox, and the PR was not listed anymore in the review requests page.

2021-04-14 16:09 UTC, guillegr123 approved these changes
Lgtm!

2021-04-14 18:29 UTC, merged