mspb-215: fix teammate device payload
2600hz/monster-ui-voip pull request #408
Opened 2022-04-15 00:14 UTC by mavriciomart

2022-04-18 17:21 UTC, harenson requested changes

2022-04-18 17:21 UTC, harenson commented on submodules/devices/devices.js
> +						ignore_completed_elsewhere: false,
This one should go within a `sip` object.

2022-04-18 17:21 UTC, harenson commented on submodules/devices/devices.js
> +						ignore_completed_elsewhere: false,
Here is the schema for devices requests https://github.com/2600hz/kazoo-crossbar/blob/master/priv/couchdb/schemas/devices.json#L315-L318

2022-04-19 17:36 UTC, mavriciomart commented on submodules/devices/devices.js
> +						ignore_completed_elsewhere: false,
Fixed :)

2022-04-22 17:40 UTC, masmerino13 approved these changes
lgtm

2022-04-22 18:24 UTC, harenson approved these changes
:+1:

2022-04-22 18:31 UTC, merged