MSPB-295,MSPB-296: Copy diagnostic data for a call instead of producing an html email link
2600hz/monster-ui-voip pull request #461
Opened 2022-09-08 21:05 UTC by oscbco

This removes the html `email link` containing `mailto:{EMAIL}?subject=Call Report: {CALL_ID}&body={CALL_DATA}` in each of the items in the Call Logs and replaces it with a `fa-clone` icon that copies to the clipboard the same information in addition to a `base64` encoded `JSON` representation of the call data that also includes all the call legs in an array.

2022-09-08 21:21 UTC, guillegr123 commented on submodules/callLogs/callLogs.js
> +				+ '\nBase64 Encoded: ' + btoa(JSON.stringify(call));
As this is a formatted text, I think it should be included in the internazionalization files

2022-09-08 21:54 UTC, oscbco commented on submodules/callLogs/callLogs.js
> +				+ '\nBase64 Encoded: ' + btoa(JSON.stringify(call));
Fixed!. Thank you.

2022-09-19 17:52 UTC, guillegr123 requested changes

2022-09-19 17:52 UTC, guillegr123 commented on submodules/callLogs/views/layout.html
> +	<div class="copy-diag-data-target"></i>
The closing tag `</i>` does not match the opening tag `<div>`

2022-09-19 19:02 UTC, guillegr123 approved these changes
Lgtm!

2022-09-20 19:37 UTC, guillegr123 commented on submodules/callLogs/callLogs.js
> +				var clipboardTarget = $('.copy-diag-data-target');
I think it would be better to search the element `copy-diag-data-target` within the call logs template, to avoid picking an element that has the same class, outside of this specific application (just in case).

2022-09-20 21:18 UTC, guillegr123 approved these changes

2022-09-21 16:24 UTC, guillegr123 approved these changes

2022-09-21 16:53 UTC, merged