MSPB-308: Check for UTF-8 character in extensions in SmartPBX
2600hz/monster-ui-voip pull request #468
Opened 2022-10-27 22:02 UTC by Isaac2600Hz

2022-10-31 17:57 UTC, guillegr123 requested changes

2022-10-31 17:57 UTC, guillegr123 commented on app.js
> +		filterNumbersToDisplay: function(number) {
I would suggest to use a name that describes better what the function does, and that it returns a boolean value. Something like `isPhoneNumberDisplayable` or `isPhoneNumberAllowed`. Or maybe `isExtensionDisplayable` or `isExtensionAllowed`, if it is only intended for extensions.

2022-10-31 17:57 UTC, guillegr123 commented on app.js
> +			var isValidPhoneNumber = monster.util.getFormatPhoneNumber(number).isValid;
If the function `filterNumbersToDisplay` is only called for extensions, it should not be necessary to check again if it is a valid phone number, because we alreadey know that we are dealing with an extension.

2022-10-31 20:27 UTC, Isaac2600Hz commented on app.js
> +			var isValidPhoneNumber = monster.util.getFormatPhoneNumber(number).isValid;
Done

2022-10-31 20:27 UTC, Isaac2600Hz commented on app.js
> +		filterNumbersToDisplay: function(number) {
Done

2022-11-01 15:14 UTC, masmerino13 requested changes
Looks really for me, I just left some comments/suggestions, let me know if there are any questions

2022-11-01 18:41 UTC, Isaac2600Hz commented on submodules/users/users.js
> +						if (self.isExtensionDisplayable(number)) {
Done

2022-11-01 18:41 UTC, Isaac2600Hz commented on submodules/users/users.js
> +								if (_.size(number) < 7) {
Done

2022-11-01 18:41 UTC, Isaac2600Hz commented on app.js
> +			var isAlphanumericExtensionsEnabled = monster.util.isFeatureAvailable('smartpbx.users.settings.utfExtensions.show');
Done

2022-11-03 15:12 UTC, guillegr123 requested changes

2022-11-03 17:44 UTC, Isaac2600Hz commented on app.js
> +			return !isAlphanumericExtension;
Done

2022-11-03 17:45 UTC, Isaac2600Hz commented on submodules/users/users.js
> +								return false;
Done

2022-11-03 17:45 UTC, Isaac2600Hz commented on submodules/users/users.js
> +					var EXTENSION_MAX_LENGTH = 7,
Done

2022-11-03 19:04 UTC, guillegr123 approved these changes
Looks good to me!

2022-11-03 19:09 UTC, masmerino13 approved these changes
no more comments to add

2022-11-03 19:09 UTC, merged