MSBP-315: Updated cross-site message based routing
2600hz/monster-ui-voip pull request #475
Opened 2022-12-15 20:26 UTC by ramandeepromana

Moved from flag/bindEvents based cross-site message routing to event subscribe.

2022-12-16 01:47 UTC, ramandeepromana commented on app.js
> +			'voip.tab.featureCodes': 'featureCodesRender'
So, when `voip.tab.`(submodule name) is received over cross-site message; voip application call for the submodule to be render.

Example: `voip.tab.myOffice` renders `myOfficeRender`/Dashboard submodule.

Yeah but during my testing `voip.myOffice.render` did not worked/rendered the submodule when cross-site message was received.

Example: `'voip.tab.myOffice': ‘voip.myOffice.render’`

2022-12-21 21:00 UTC, azefiel commented on app.js
> +			'voip.tab.featureCodes': 'featureCodesRender'
It might have to do with the fact that the voip app was not loaded yet, and therefor has not subscribed to those topics yet 🤔
We might have to have a mechanism that first loads the app related to the topic (in this case voip) and once loaded trigger the topic in question.

2022-12-28 22:36 UTC, ramandeepromana commented on app.js
> +			'voip.tab.featureCodes': 'featureCodesRender'
I tested again and it looks like that even when the application (_voip/SmartPBX in this case_) is loaded;

& it does't work and I can see `console.warn('The topic ' + topic + ' does not have a callback');` [monster.js](https://github.com/2600hz/monster-ui/blob/9f5ebb4719d7c6137aab2ca421610b17bdc3552d/src/js/lib/monster.js#L425) in the DevTools to

`self.callback.call( context, data, env );` [postal.js](https://github.com/postaljs/postal.js/blob/d9c477de9301221be99eb2bd6c4091738100ed81/lib/postal.js#L172)

🤔 is it possible to we can't do topic to topic or I'm getting it wrong/going into wrong direction

Example: `voip.tab.myOffice` to `voip.myOffice.render` in `voip/app.js` and `voip.myOffice.render` to `myOfficeRender` method at the end in `myOffice.js`

2022-12-28 22:38 UTC, ramandeepromana commented on app.js
> +			'voip.tab.featureCodes': 'featureCodesRender'
Moreover, from the app should be loaded discussion. I believe we should have validation for that in the core/default opt-out (_only go with publication and trigger flow if the application is open by the end user_)

				const activeApp = monster.apps.getActiveApp();
				const triggerApp = topic.substring(0, topic.indexOf('.'));

				if (triggerApp !== activeApp) {
					return;
				}

2023-03-07 15:37 UTC, ramandeepromana commented
Adding @guillegr123 to PR https://github.com/2600hz/monster-ui/pull/1042 and https://github.com/2600hz/monster-ui-voip/pull/475 as @joristirado is not longer available 🥲

2023-10-13 18:24 UTC, guillegr123 requested changes

2023-10-13 18:24 UTC, guillegr123 commented on app.js
> +			monster.sub('core.crossSiteMessage.' + app.name, function(topic) {
Add this subscription to the collection of subscriptions for this module at the top, to let Monster UI handle it.

2023-10-13 18:27 UTC, guillegr123 commented
@ramandeepromana if possible, do a merge or rebase of this branch with master, in order to fix the CI builds.

2023-11-11 00:30 UTC, guillegr123 requested changes

2023-11-11 00:30 UTC, guillegr123 commented on app.js
> +			monster.pub(crossSiteMessageTopic);
`parent` parameter is missing. 
```suggestion
			monster.pub(crossSiteMessageTopic, { parent: container });
```

2023-11-15 22:16 UTC, guillegr123 approved these changes
Lgtm!

2023-11-16 11:56 UTC, merged