MSPB-253: Add call-forwarding app.
2600hz/monster-ui-voip pull request #493
Opened 2023-04-02 10:06 UTC by Isaac2600Hz

2023-04-02 23:29 UTC, pcandia commented on i18n/en-US.json
> +							"helpText": "Receive a prompt to accept forwarded calls. This prevents voicemails from being associated with the 'Forward To' number."
I wouldn't suggest using single quotes, instead you can do 
```suggestion
							"helpText": "Receive a prompt to accept forwarded calls. This prevents voicemails from being associated with the \"Forward To\" number."
```

2023-04-02 23:38 UTC, pcandia commented on submodules/usersCallForwarding/usersCallForwarding.js
> +                        if (strategy != 'off' || strategy != 'selective') {
Instead i would do this:

```suggestion
                        if (strategy !== 'off' || strategy !== 'selective') {
```

2023-04-03 00:22 UTC, pcandia requested changes
I also have one question, why was the "Call Forwarding" option moved to the left of "Caller-ID number"? In the mockup I see it as the second option, which is how it was before:
![image](https://user-images.githubusercontent.com/16088958/229387041-f862de09-5479-4900-8406-34f429d04d36.png)

Also, when testing the changes I saw a few issues, the first ones are that saving any option causes issues:
<img width="987" alt="2023-04-02_19-07" src="https://user-images.githubusercontent.com/16088958/229387089-6bdc149f-5d9b-4e71-8f6c-c4e80ec69f94.png">
<img width="1203" alt="2023-04-02_19-23" src="https://user-images.githubusercontent.com/16088958/229387096-305d64f7-4211-4f17-b018-7685c4429085.png">

<img width="845" alt="2023-04-02_20-22" src="https://user-images.githubusercontent.com/16088958/229387242-4028a0bb-1c04-417a-99cc-eba79ff0941a.png">

Also, I would recommend checking the linter by running `gulp lint --app=voip`
You can see a bunch of suggestions which some are part of my review, please let me know if you have any issues running this or understanding what its asking you to do, some examples are these:
![image](https://user-images.githubusercontent.com/16088958/229387395-fd16bb4e-bc0a-4eb0-be3c-7b9d0ec72e0c.png)

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/usersCallForwarding.scss
> +    color: rgb(14, 14, 15);
instead of rgb, we prefer to use the hex.  You can import the values from `_base.scss` https://github.com/2600hz/monster-ui/blob/master/src/css/partials/_base.scss

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/usersCallForwarding.scss
> +.call-forwarding-popup {
```suggestion
@import '../../../css/partials/base';

.call-forwarding-popup {
```

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/usersCallForwarding.scss
> +    background: rgb(255, 255, 255);
For example, after importing the `_base.scss`, you do the following here:
```suggestion
    background: $white;
```

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                Forward calls from
Do not hardcode this, instead add it to the languages file.

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                {{#monsterRadio @root.i18n.users.callForwarding.strategies.selective.all }}
You don't need the `@root` in this case,
```suggestion
                {{#monsterRadio i18n.users.callForwarding.strategies.selective.all }}
```

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                    {{#monsterRadio @root.i18n.users.callForwarding.strategies.selective.specific }}
same here and in few others. You would only need inside loops
```suggestion
                    {{#monsterRadio i18n.users.callForwarding.strategies.selective.specific }}
```

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                Forward calls to
We don't want to hardcode values, instead add it to the language files please

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                                    {{/select}}
Here it's just the spacing.

```suggestion
                                    {{#select selectedVoicemailId}}
                                          {{#each voicemails as |voicemail|}}
                                          <option value="{{voicemail.id}}">
                                              {{voicemail.name}}
                                          </option>
                                          {{/each}}
                                    {{/select}}
```

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                Active duration
same here, do not hardcode it.

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                Remove rule
and here.

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/complexStrategy.html
> +                    {{/monsterCheckbox}}
Just the spacing here and in other places
```suggestion
                    {{#monsterCheckbox "large-checkbox"}}
                        <input type="checkbox" name="{{strategy}}.isEnabled" {{#if enabled}} checked="checked" {{/if}} />
                    {{/monsterCheckbox}}
```

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/listing.html
> +                </th>
please do not hardcode values, instead we want to add them to the languages files

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/options.html
> +        {{@root.i18n.users.callForwarding.strategies.common.options.title}}
```suggestion
        {{i18n.users.callForwarding.strategies.common.options.title}}
```

2023-04-03 00:22 UTC, pcandia commented on submodules/usersCallForwarding/views/simpleStrategy.html
> +            {{#monsterRadio @root.i18n.users.callForwarding.strategies.common.voicemail.label }}
```suggestion
            {{#monsterRadio i18n.users.callForwarding.strategies.common.voicemail.label }}
```

2023-04-03 12:49 UTC, ramandeepromana commented
> I also have one question, why was the "Call Forwarding" option moved to the left of "Caller-ID number"? In the mockup I see it as the second option, which is how it was before: ![image](https://user-images.githubusercontent.com/16088958/229387041-f862de09-5479-4900-8406-34f429d04d36.png)
> 
I believe that part was done by @joristirado and @Isaac2600Hz just worked on top of it (_if I'm not wrong 😄_)

2023-04-03 14:27 UTC, pcandia commented
@ramandeepromana yeah, i understand. It's an easy change and also we should always try to follow the mockups. So my comments were based on the mockups https://app.abstract.com/share/1b55ca8e-e43f-429c-969b-22f99f2491bc

2023-04-05 23:14 UTC, ramandeepromana commented
@pcandia @guillegr123 apologies for the trouble/please wait on the review as there are going to be new changes as well as fixes to Call Forwarding/Failover🙇🏼

2023-04-13 21:24 UTC, ramandeepromana commented
<img width="1270" alt="Screenshot 2023-04-13 at 5 51 54 PM" src="https://user-images.githubusercontent.com/78377672/231882357-9a4d03cd-d946-4fca-82d1-413c9c142b21.png">
I kept getting same error for when selecting Voicemail options under unconditional/Always On, Busy and no_answer/No Answer.

The phone number section works as per my testing. However, please remove unnecessary data from the payload/being added to the user document.
```
{
   "data":{
      "call_forward":{
         "enabled":true,
         "keep_caller_id":true,
         "direct_calls_only":true,
         "require_keypress":true,
         "ignore_early_media":true,
         "substitute":false,
         "unconditional":{
            "number":{phone_number},
            "enabled":true
         },
         "busy":null,
         "no_answer":null,
         "selective":null
      },
      "extra":{
         "mapFeatures":{
            "call_forwarding":{
               "active":true
            }
         }
      },
      "ui_metadata":{
         "version":"4.3.0",
         "ui":"monster-ui",
         "origin":"voip"
      }
   }
}
```
Moreover, as per todays conversation please move the Additional option from outside to inside of the `call_forward` selection object, below is example of unconditional/Always On
```
{
   "data":{
      "call_forward":{
         "unconditional":{
            "number":{phone_number},
            "enabled":true,
            "keep_caller_id":true,
            "direct_calls_only":true,
            "require_keypress":true,
            "ignore_early_media":true,
            "substitute":false
         }
      }
   }
}
```
The voicemail API Request error out for Selective. However, there is no `"skip_module": true` for `"module": "user"` in the API Request and for when Phone Number is selected there is no use of `match_list` with `"call_forward":{ "selective":{` and not really sure why we are doing POST to `/v2/accounts/{account_id}/callflows/{callflow_id}`

Lastly, comment/issues above are only for when saving/making API Request and not for when getting the save data for display/UI defects.

@Isaac2600Hz

2023-04-13 21:34 UTC, Isaac2600Hz commented
> <img alt="Screenshot 2023-04-13 at 5 51 54 PM" width="1270" src="https://user-images.githubusercontent.com/78377672/231882357-9a4d03cd-d946-4fca-82d1-413c9c142b21.png">
> 
> I kept getting same error for when selecting Voicemail options under unconditional/Always On, Busy and no_answer/No Answer.
> The phone number section works as per my testing. However, please remove unnecessary data from the payload/being added to the user document.
> 
> ```
> {
>    "data":{
>       "call_forward":{
>          "enabled":true,
>          "keep_caller_id":true,
>          "direct_calls_only":true,
>          "require_keypress":true,
>          "ignore_early_media":true,
>          "substitute":false,
>          "unconditional":{
>             "number":{phone_number},
>             "enabled":true
>          },
>          "busy":null,
>          "no_answer":null,
>          "selective":null
>       },
>       "extra":{
>          "mapFeatures":{
>             "call_forwarding":{
>                "active":true
>             }
>          }
>       },
>       "ui_metadata":{
>          "version":"4.3.0",
>          "ui":"monster-ui",
>          "origin":"voip"
>       }
>    }
> }
> ```
> 
> Moreover, as per todays conversation please move the Additional option from outside to inside of the `call_forward` selection object, below is example of unconditional/Always On
> 
> ```
> {
>    "data":{
>       "call_forward":{
>          "unconditional":{
>             "number":{phone_number},
>             "enabled":true,
>             "keep_caller_id":true,
>             "direct_calls_only":true,
>             "require_keypress":true,
>             "ignore_early_media":true,
>             "substitute":false
>          }
>       }
>    }
> }
> ```
> 
> The voicemail API Request error out for Selective. However, there is no `"skip_module": true` for `"module": "user"` in the API Request and for when Phone Number is selected there is no use of `match_list` with `"call_forward":{ "selective":{` and not really sure why we are doing POST to `/v2/accounts/{account_id}/callflows/{callflow_id}`
> 
> Lastly, comment/issues above are only for when saving/making API Request and not for when getting the save data for display/UI defects.
> 
> @Isaac2600Hz

What exactly is that "Unnecesary data"? All the data in that document is being used to render/modify different parts of the UI.

2023-04-14 14:59 UTC, ramandeepromana commented
@Isaac2600Hz Ah sorry for the confusion 😅 let me try again.
Below is the payload for `call_forward` that we have right now for API request(_s_)
```
{
   "data":{
      "call_forward":{
         "enabled":true,
         "keep_caller_id":true,
         "direct_calls_only":true,
         "require_keypress":true,
         "ignore_early_media":true,
         "substitute":false,
         "unconditional":{
            "number":{phone_number},
            "enabled":true
         },
         "busy":null,
         "no_answer":null,
         "selective":null
      },
      "extra":{
         "mapFeatures":{
            "call_forwarding":{
               "active":true
            }
         }
      },
      "ui_metadata":{
         "version":"4.3.0",
         "ui":"monster-ui",
         "origin":"voip"
      }
   }
}
```
and the correct should be
```
{
   "data":{
      "call_forward":{
         "enabled":true,
         "keep_caller_id":true,
         "direct_calls_only":true,
         "require_keypress":true,
         "ignore_early_media":true,
         "substitute":false,
         "unconditional":{
            "number":{phone_number},
            "enabled":true
         }
      }
   }
}
```
So, as you can see we have removed 2 things

- 1st

```
         "busy":null,
         "no_answer":null,
         "selective":null
```
We don't need to add those to the `call_forward` as those props serve no purpose in the user document/backend (_from UI prospective if one option is enabled others should be assumed disabled_)

- 2nd:

```
      "extra":{
         "mapFeatures":{
            "call_forwarding":{
               "active":true
            }
         }
      },
```
Instead of adding this we should be using/able to use
```
      "call_forward":{
         "enabled":true,
```
General example: If `"extra.mapFeatures.call_forwarding.active": true` is being used as data point by the frontend it should not leak to the user document (_again, those props serve no purpose in the user document/backend_)
However, if that is being used for "render/modify different parts of the UI" that shouldn't be like that because if someone made changed to `call_forward` using API than that would definitely break things in the UI side.

@guillegr123 @pcandia could you please correct me if I'm wrong 🙇🏻

2023-04-14 15:03 UTC, ramandeepromana commented
Oh and @Isaac2600Hz please check lint by running `gulp lint --app=voip` as of commit https://github.com/2600hz/monster-ui-voip/pull/493/commits/37fff3cf1b69895bc86ecd08439d445f23b16781 🙂 and let me know if you have any issues or wants to know what that is 🙃

2023-04-14 17:17 UTC, pcandia commented
@ramandeepromana yes you are correct, we should only send the data needed for the specific setting.

2023-04-20 21:07 UTC, ramandeepromana commented
- When selecting the Voicemail option with `Forward direct calls Only`

```
{
   "data":{
      "call_forward":{
         "enabled":true,
         "unconditional":{
            "enabled":true,
            "keep_caller_id":false,
            "direct_calls_only":true,
            "require_keypress":false,
            "ignore_early_media":false,
            "substitute":false,
            "number":"123"
         },
         "busy":null,
         "no_answer":null,
         "selective":null
      },
      "call_forward_vm":{
         "unconditional":{
            "enabled":true,
            "voicemail":"aa0b782aa3c3bd2185dd74aa972cd6df",
            "direct_calls_only":false
         },
         "busy":null,
         "no_answer":null,
         "selective":null
      },
      "ui_metadata":{
         "version":"4.3.0",
         "ui":"monster-ui",
         "origin":"voip"
      }
   }
}
```

1. `"direct_calls_only":false` should be `true`
2. not sure why we are adding `call_forward` with `unconditional/"number":"123"` wit call forwarding set  `"enabled":true,` for when Voicemail is selected
3. other options with `:null,` are still present
4. selected target voicemail is not being selected

- When disabling voicemail Option the payloads for user document should be

```
{
   "data":{
      "call_forward_vm":{
         "unconditional":{
            "enabled":true,
            "voicemail":"aa0b782aa3c3bd2185dd74aa972cd6df",
            "direct_calls_only":true
         }
      }
   }
}
```
Instead of below
```
{
   "data":{
      "call_forward":{
         "enabled":false,
         "unconditional":null,
         "busy":null,
         "no_answer":null,
         "selective":null
      },
      "call_forward_vm":{
         "off":{
            "enabled":false,
            "voicemail":"",
            "direct_calls_only":false
         },
         "unconditional":null,
         "busy":null,
         "no_answer":null,
         "selective":null
      },
      "ui_metadata":{
         "version":"4.3.0",
         "ui":"monster-ui",
         "origin":"voip"
      }
   }
}
```

- When selecting the Phone number option

```
      "call_forward":{
         "enabled":true,
         "unconditional":{
            "enabled":true,
            "keep_caller_id":true,
            "direct_calls_only":true,
            "require_keypress":true,
            "ignore_early_media":true,
            "substitute":false,
            "number":"123"
         },
         "busy":null,
         "no_answer":null,
         "selective":null
      }
```

1. `"number":"123"` us being passed instead of the input number
2. other options with `:null,` are still present
3. not sure why were are making PATCH request to` /v2/accounts/{account_id}/callflows/{callflow_id}`

Other general issues (_not including selective_)

1. icon doesn't display the turned on state for when call forwarding is enabled
2. when GET the UI doesn't display the data
3. radio button behaviour isn't as expected

@Isaac2600Hz above are the things/issues that I found/saw per my testing. Also, how are you testing the new code changes 🤔 

@guillegr123 @pcandia please add if I missed something and apologies for the ping.

2023-04-20 21:10 UTC, ramandeepromana commented
Oh and `gulp lint --app=voip` 😄 
```
monster-ui/src/apps/voip/submodules/usersCallForwarding/usersCallForwarding.js
    8:5   error  'days' is assigned a value but never used. Allowed unused vars must match /_|self|toastr|chosen|FileSaver|.*[cC]hart/u  no-unused-vars
  489:45  error  Block must not be padded by blank lines                                                                                 padded-blocks
```

2023-04-20 22:13 UTC, Isaac2600Hz commented
- Again, those `null` options are needed to avoid the user document getting overloaded with other options, removing those `null` options in `call_forward_vm` and `call_forward` would result, eventually, in something like this

```{
    "data":{
       "call_forward":{
          "enabled":true,
          "unconditional":{
             "enabled":true,
             "keep_caller_id":false,
             "direct_calls_only":true,
             "require_keypress":false,
             "ignore_early_media":false,
             "substitute":false,
             "number":"123"
          },
          "busy":{
            "enabled":true,
            "keep_caller_id":false,
            "direct_calls_only":true,
            "require_keypress":false,
            "ignore_early_media":false,
            "substitute":false,
            "number":"123"
         },
          "no_answer":{
            "enabled":true,
            "keep_caller_id":false,
            "direct_calls_only":true,
            "require_keypress":false,
            "ignore_early_media":false,
            "substitute":false,
            "number":"123"
         },
          "selective":{
            "enabled":true,
            "keep_caller_id":false,
            "direct_calls_only":true,
            "require_keypress":false,
            "ignore_early_media":false,
            "substitute":false,
            "number":"123"
         }
       },
       "call_forward_vm":{
          "unconditional":{
             "enabled":true,
             "voicemail":"aa0b782aa3c3bd2185dd74aa972cd6df",
             "direct_calls_only":false
          },
          "busy":null,
          "no_answer":null,
          "selective":null
       },
       "ui_metadata":{
          "version":"4.3.0",
          "ui":"monster-ui",
          "origin":"voip"
       }
    }
 }
 ```

- Regarding ` /v2/accounts/{account_id}/callflows/{callflow_id}` 
Dont we need to modify `"skip_module": true` for the skip to voicemail box?
https://2600hz-commercial.atlassian.net/browse/MSPB-253?focusedCommentId=39994

- Regarding the Number "123" when voicemail is selected, we need to give `number` a value other wise we'll get an error from the API
![image](https://user-images.githubusercontent.com/111767361/233497645-e1aadf7c-229b-42b4-af7f-9080538de3b5.png)

- I do agree with the rest I think

2023-04-27 15:15 UTC, ramandeepromana commented
@Isaac2600Hz apologies for the delay and I tested new changes as requested/below are the things that I found

1. When selecting any option for the fist time the `Phone Number` radio button is `selected` and it should be `Voicemail` as per the mockups
2. Need to fix the post save process as without refresh incorrect/old information is displayed
3. When selecting Voicemail option the voicemail box is not being changed in the user callfow (_the default voicemail box is present_)
4. Need to add callflow change for when user disables `call_forward`

Only tested `disabled`/Off, `unconditional`/Always, `busy`/Busy and `no_answer`/No Answer

2023-04-27 15:16 UTC, ramandeepromana commented
@Isaac2600Hz I believe we should save the original user's voicemail box id and add that to request for when user is switching from Voicemail Box to Phone Number or even when disabling `call_forward` (_as I can see users complain that call or not going to their voicemail boxes_) 

- Oh and may be we should move call_forward_vm to something like how it's in the account document `"ui_help":{ "call_forward":` or `"smartpbx":{ "call_forward":`  for how it's in user document

CC'ing @guillegr123 on the last point 🙂

2023-09-04 17:11 UTC, pcandia requested changes
Currently when clicking on "custom" the options for it is only displayed in the first option.  Also, the "Additional options" are displayed even when it should be displayed for "Phone Number"
![image](https://github.com/2600hz/monster-ui-voip/assets/16088958/6a6593c0-cf1b-487d-acc4-410bc43e40a3)


And after saving it, only the first row is displayed.

2023-09-04 18:26 UTC, Isaac2600Hz commented
> Currently when clicking on "custom" the options for it is only displayed in the first option. Also, the "Additional options" are displayed even when it should be displayed for "Phone Number" ![image](https://user-images.githubusercontent.com/16088958/265516723-6a6593c0-cf1b-487d-acc4-410bc43e40a3.png)
> 
> And after saving it, only the first row is displayed.

T

> Currently when clicking on "custom" the options for it is only displayed in the first option. Also, the "Additional options" are displayed even when it should be displayed for "Phone Number" ![image](https://user-images.githubusercontent.com/16088958/265516723-6a6593c0-cf1b-487d-acc4-410bc43e40a3.png)
> 
> And after saving it, only the first row is displayed.

Fixed

2023-09-26 17:25 UTC, ramandeepromana commented on submodules/usersCallForwarding/usersCallForwarding.js
> +							console.log('isDefaultMatchList');
I believe for best practices, we should try to `keep console.log` and similar debugging statements out of our commits. Could you please remove them before merging?

2023-12-14 22:34 UTC, pcandia approved these changes
This looks good to me.  Also, after talking to Ramen, he explained to me that the design doesn't need to match the mockups as they are for comm.land, he also said that there won't be additional options for the "voicemail" selection because in Kazoo there is no forward to voicemail and they are manipulating user's default callflow.

2023-12-15 16:58 UTC, merged